// This file is autogenerated from: unstable/text-input-v3/text-input-unstable-v3.xml
// Do not edit

// Package text implements the text_input_unstable_v3 protocol
package text

import (
	"sync"

)
// ZwpInputV3ChangeCauseInputMethod means input method caused the change
const ZwpInputV3ChangeCauseInputMethod = 0

// ZwpInputV3ChangeCauseOther means something else than the input method caused the change
const ZwpInputV3ChangeCauseOther = 1

// ZwpInputV3ContentHintNone means no special behavior
const ZwpInputV3ContentHintNone = 0x0

// ZwpInputV3ContentHintCompletion means suggest word completions
const ZwpInputV3ContentHintCompletion = 0x1

// ZwpInputV3ContentHintSpellcheck means suggest word corrections
const ZwpInputV3ContentHintSpellcheck = 0x2

// ZwpInputV3ContentHintAutoCapitalization means switch to uppercase letters at the start of a sentence
const ZwpInputV3ContentHintAutoCapitalization = 0x4

// ZwpInputV3ContentHintLowercase means prefer lowercase letters
const ZwpInputV3ContentHintLowercase = 0x8

// ZwpInputV3ContentHintUppercase means prefer uppercase letters
const ZwpInputV3ContentHintUppercase = 0x10

// ZwpInputV3ContentHintTitlecase means prefer casing for titles and headings (can be language dependent)
const ZwpInputV3ContentHintTitlecase = 0x20

// ZwpInputV3ContentHintHiddenText means characters should be hidden
const ZwpInputV3ContentHintHiddenText = 0x40

// ZwpInputV3ContentHintSensitiveData means typed text should not be stored
const ZwpInputV3ContentHintSensitiveData = 0x80

// ZwpInputV3ContentHintLatin means just Latin characters should be entered
const ZwpInputV3ContentHintLatin = 0x100

// ZwpInputV3ContentHintMultiline means the text input is multiline
const ZwpInputV3ContentHintMultiline = 0x200

// ZwpInputV3ContentPurposeNormal means default input, allowing all characters
const ZwpInputV3ContentPurposeNormal = 0

// ZwpInputV3ContentPurposeAlpha means allow only alphabetic characters
const ZwpInputV3ContentPurposeAlpha = 1

// ZwpInputV3ContentPurposeDigits means allow only digits
const ZwpInputV3ContentPurposeDigits = 2

// ZwpInputV3ContentPurposeNumber means input a number (including decimal separator and sign)
const ZwpInputV3ContentPurposeNumber = 3

// ZwpInputV3ContentPurposePhone means input a phone number
const ZwpInputV3ContentPurposePhone = 4

// ZwpInputV3ContentPurposeUrl means input an URL
const ZwpInputV3ContentPurposeUrl = 5

// ZwpInputV3ContentPurposeEmail means input an email address
const ZwpInputV3ContentPurposeEmail = 6

// ZwpInputV3ContentPurposeName means input a name of a person
const ZwpInputV3ContentPurposeName = 7

// ZwpInputV3ContentPurposePassword means input a password (combine with sensitive_data hint)
const ZwpInputV3ContentPurposePassword = 8

// ZwpInputV3ContentPurposePin means input is a numeric password (combine with sensitive_data hint)
const ZwpInputV3ContentPurposePin = 9

// ZwpInputV3ContentPurposeDate means input a date
const ZwpInputV3ContentPurposeDate = 10

// ZwpInputV3ContentPurposeTime means input a time
const ZwpInputV3ContentPurposeTime = 11

// ZwpInputV3ContentPurposeDatetime means input a date and time
const ZwpInputV3ContentPurposeDatetime = 12

// ZwpInputV3ContentPurposeTerminal means input for a terminal
const ZwpInputV3ContentPurposeTerminal = 13

// ZwpInputV3 text input
type ZwpInputV3 struct {
	BaseProxy
	mu sync.RWMutex
	privateZwpInputV3Enters map[ZwpInputV3EnterHandler]struct{}
	privateZwpInputV3Leaves map[ZwpInputV3LeaveHandler]struct{}
	privateZwpInputV3PreeditStrings map[ZwpInputV3PreeditStringHandler]struct{}
	privateZwpInputV3CommitStrings map[ZwpInputV3CommitStringHandler]struct{}
	privateZwpInputV3DeleteSurroundingTexts map[ZwpInputV3DeleteSurroundingTextHandler]struct{}
	privateZwpInputV3Dones map[ZwpInputV3DoneHandler]struct{}
}
// initZwpInputV3 initializes the ZwpInputV3 object's handler maps
func (ret *ZwpInputV3) initZwpInputV3() {
	ret.privateZwpInputV3Enters = make(map[ZwpInputV3EnterHandler]struct{})
	ret.privateZwpInputV3Leaves = make(map[ZwpInputV3LeaveHandler]struct{})
	ret.privateZwpInputV3PreeditStrings = make(map[ZwpInputV3PreeditStringHandler]struct{})
	ret.privateZwpInputV3CommitStrings = make(map[ZwpInputV3CommitStringHandler]struct{})
	ret.privateZwpInputV3DeleteSurroundingTexts = make(map[ZwpInputV3DeleteSurroundingTextHandler]struct{})
	ret.privateZwpInputV3Dones = make(map[ZwpInputV3DoneHandler]struct{})
}
// NewZwpInputV3 is a constructor for the ZwpInputV3 object
func NewZwpInputV3(ctx *Context) *ZwpInputV3 {
	ret := new(ZwpInputV3)
	ret.initZwpInputV3()
	ctx.Register(ret)
	return ret
}
// Destroy Destroy the wp_text_input
func (p *ZwpInputV3) Destroy() (error) {
	
	return p.Context().SendRequest(p, 0)
}
// Enable Request text input to be enabled
func (p *ZwpInputV3) Enable() (error) {
	
	return p.Context().SendRequest(p, 1)
}
// Disable Disable text input on a surface
func (p *ZwpInputV3) Disable() (error) {
	
	return p.Context().SendRequest(p, 2)
}
// SetSurroundingText sets the surrounding text
func (p *ZwpInputV3) SetSurroundingText(Text string, Cursor int32, Anchor int32) (error) {
	
	return p.Context().SendRequest(p, 3, Text, Cursor, Anchor)
}
// SetChangeCause indicates the cause of surrounding text change
func (p *ZwpInputV3) SetChangeCause(Cause uint32) (error) {
	
	return p.Context().SendRequest(p, 4, Cause)
}
// SetContentType set content purpose and hint
func (p *ZwpInputV3) SetContentType(Hint uint32, Purpose uint32) (error) {
	
	return p.Context().SendRequest(p, 5, Hint, Purpose)
}
// SetCursorRectangle set cursor position
func (p *ZwpInputV3) SetCursorRectangle(X int32, Y int32, Width int32, Height int32) (error) {
	
	return p.Context().SendRequest(p, 6, X, Y, Width, Height)
}
// Commit commit state
func (p *ZwpInputV3) Commit() (error) {
	
	return p.Context().SendRequest(p, 7)
}
// Dispatch dispatches event for object ZwpInputV3
func (p *ZwpInputV3) Dispatch(event *Event) {
	switch event.Opcode {
	case 0:
		if len(p.privateZwpInputV3Enters) > 0 {
			ev := ZwpInputV3EnterEvent{}
			ev.Surface = SafeCast[*Surface](event.Proxy(p.Context()))
			p.mu.RLock()
			for h := range p.privateZwpInputV3Enters {
				h.HandleZwpInputV3Enter(ev)
			}
			p.mu.RUnlock()
		}
	case 1:
		if len(p.privateZwpInputV3Leaves) > 0 {
			ev := ZwpInputV3LeaveEvent{}
			ev.Surface = SafeCast[*Surface](event.Proxy(p.Context()))
			p.mu.RLock()
			for h := range p.privateZwpInputV3Leaves {
				h.HandleZwpInputV3Leave(ev)
			}
			p.mu.RUnlock()
		}
	case 2:
		if len(p.privateZwpInputV3PreeditStrings) > 0 {
			ev := ZwpInputV3PreeditStringEvent{}
			ev.Text = event.String()
			ev.CursorBegin = event.Int32()
			ev.CursorEnd = event.Int32()
			p.mu.RLock()
			for h := range p.privateZwpInputV3PreeditStrings {
				h.HandleZwpInputV3PreeditString(ev)
			}
			p.mu.RUnlock()
		}
	case 3:
		if len(p.privateZwpInputV3CommitStrings) > 0 {
			ev := ZwpInputV3CommitStringEvent{}
			ev.Text = event.String()
			p.mu.RLock()
			for h := range p.privateZwpInputV3CommitStrings {
				h.HandleZwpInputV3CommitString(ev)
			}
			p.mu.RUnlock()
		}
	case 4:
		if len(p.privateZwpInputV3DeleteSurroundingTexts) > 0 {
			ev := ZwpInputV3DeleteSurroundingTextEvent{}
			ev.BeforeLength = event.Uint32()
			ev.AfterLength = event.Uint32()
			p.mu.RLock()
			for h := range p.privateZwpInputV3DeleteSurroundingTexts {
				h.HandleZwpInputV3DeleteSurroundingText(ev)
			}
			p.mu.RUnlock()
		}
	case 5:
		if len(p.privateZwpInputV3Dones) > 0 {
			ev := ZwpInputV3DoneEvent{}
			ev.Serial = event.Uint32()
			p.mu.RLock()
			for h := range p.privateZwpInputV3Dones {
				h.HandleZwpInputV3Done(ev)
			}
			p.mu.RUnlock()
		}

	}
}
// ZwpInputV3EnterEvent is the enter event
type ZwpInputV3EnterEvent struct {
	// Surface is the 
	Surface *Surface

}
// ZwpInputV3LeaveEvent is the leave event
type ZwpInputV3LeaveEvent struct {
	// Surface is the 
	Surface *Surface

}
// ZwpInputV3PreeditStringEvent is the pre-edit
type ZwpInputV3PreeditStringEvent struct {
	// Text is the 
	Text string
	// CursorBegin is the 
	CursorBegin int32
	// CursorEnd is the 
	CursorEnd int32

}
// ZwpInputV3CommitStringEvent is the text commit
type ZwpInputV3CommitStringEvent struct {
	// Text is the 
	Text string

}
// ZwpInputV3DeleteSurroundingTextEvent is the delete surrounding text
type ZwpInputV3DeleteSurroundingTextEvent struct {
	// BeforeLength is the length of text before current cursor position
	BeforeLength uint32
	// AfterLength is the length of text after current cursor position
	AfterLength uint32

}
// ZwpInputV3DoneEvent is the apply changes
type ZwpInputV3DoneEvent struct {
	// Serial is the 
	Serial uint32

}
// ZwpInputV3EnterHandler is the handler interface for ZwpInputV3EnterEvent
type ZwpInputV3EnterHandler interface {
	HandleZwpInputV3Enter(ZwpInputV3EnterEvent)
}

// AddEnterHandler adds the Enter handler
func (p *ZwpInputV3) AddEnterHandler(h ZwpInputV3EnterHandler) {
	if h != nil {
		p.mu.Lock()
		p.privateZwpInputV3Enters[h] = struct{}{}
		p.mu.Unlock()
	}
}

// RemoveEnterHandler removes the Enter handler
func (p *ZwpInputV3) RemoveEnterHandler(h ZwpInputV3EnterHandler) {
	p.mu.Lock()
	defer p.mu.Unlock()

	delete (p.privateZwpInputV3Enters, h)
}
// ZwpInputV3LeaveHandler is the handler interface for ZwpInputV3LeaveEvent
type ZwpInputV3LeaveHandler interface {
	HandleZwpInputV3Leave(ZwpInputV3LeaveEvent)
}

// AddLeaveHandler adds the Leave handler
func (p *ZwpInputV3) AddLeaveHandler(h ZwpInputV3LeaveHandler) {
	if h != nil {
		p.mu.Lock()
		p.privateZwpInputV3Leaves[h] = struct{}{}
		p.mu.Unlock()
	}
}

// RemoveLeaveHandler removes the Leave handler
func (p *ZwpInputV3) RemoveLeaveHandler(h ZwpInputV3LeaveHandler) {
	p.mu.Lock()
	defer p.mu.Unlock()

	delete (p.privateZwpInputV3Leaves, h)
}
// ZwpInputV3PreeditStringHandler is the handler interface for ZwpInputV3PreeditStringEvent
type ZwpInputV3PreeditStringHandler interface {
	HandleZwpInputV3PreeditString(ZwpInputV3PreeditStringEvent)
}

// AddPreeditStringHandler adds the PreeditString handler
func (p *ZwpInputV3) AddPreeditStringHandler(h ZwpInputV3PreeditStringHandler) {
	if h != nil {
		p.mu.Lock()
		p.privateZwpInputV3PreeditStrings[h] = struct{}{}
		p.mu.Unlock()
	}
}

// RemovePreeditStringHandler removes the PreeditString handler
func (p *ZwpInputV3) RemovePreeditStringHandler(h ZwpInputV3PreeditStringHandler) {
	p.mu.Lock()
	defer p.mu.Unlock()

	delete (p.privateZwpInputV3PreeditStrings, h)
}
// ZwpInputV3CommitStringHandler is the handler interface for ZwpInputV3CommitStringEvent
type ZwpInputV3CommitStringHandler interface {
	HandleZwpInputV3CommitString(ZwpInputV3CommitStringEvent)
}

// AddCommitStringHandler adds the CommitString handler
func (p *ZwpInputV3) AddCommitStringHandler(h ZwpInputV3CommitStringHandler) {
	if h != nil {
		p.mu.Lock()
		p.privateZwpInputV3CommitStrings[h] = struct{}{}
		p.mu.Unlock()
	}
}

// RemoveCommitStringHandler removes the CommitString handler
func (p *ZwpInputV3) RemoveCommitStringHandler(h ZwpInputV3CommitStringHandler) {
	p.mu.Lock()
	defer p.mu.Unlock()

	delete (p.privateZwpInputV3CommitStrings, h)
}
// ZwpInputV3DeleteSurroundingTextHandler is the handler interface for ZwpInputV3DeleteSurroundingTextEvent
type ZwpInputV3DeleteSurroundingTextHandler interface {
	HandleZwpInputV3DeleteSurroundingText(ZwpInputV3DeleteSurroundingTextEvent)
}

// AddDeleteSurroundingTextHandler adds the DeleteSurroundingText handler
func (p *ZwpInputV3) AddDeleteSurroundingTextHandler(h ZwpInputV3DeleteSurroundingTextHandler) {
	if h != nil {
		p.mu.Lock()
		p.privateZwpInputV3DeleteSurroundingTexts[h] = struct{}{}
		p.mu.Unlock()
	}
}

// RemoveDeleteSurroundingTextHandler removes the DeleteSurroundingText handler
func (p *ZwpInputV3) RemoveDeleteSurroundingTextHandler(h ZwpInputV3DeleteSurroundingTextHandler) {
	p.mu.Lock()
	defer p.mu.Unlock()

	delete (p.privateZwpInputV3DeleteSurroundingTexts, h)
}
// ZwpInputV3DoneHandler is the handler interface for ZwpInputV3DoneEvent
type ZwpInputV3DoneHandler interface {
	HandleZwpInputV3Done(ZwpInputV3DoneEvent)
}

// AddDoneHandler adds the Done handler
func (p *ZwpInputV3) AddDoneHandler(h ZwpInputV3DoneHandler) {
	if h != nil {
		p.mu.Lock()
		p.privateZwpInputV3Dones[h] = struct{}{}
		p.mu.Unlock()
	}
}

// RemoveDoneHandler removes the Done handler
func (p *ZwpInputV3) RemoveDoneHandler(h ZwpInputV3DoneHandler) {
	p.mu.Lock()
	defer p.mu.Unlock()

	delete (p.privateZwpInputV3Dones, h)
}
// ZwpInputManagerV3 text input manager
type ZwpInputManagerV3 struct {
	BaseProxy
}
// NewZwpInputManagerV3 is a constructor for the ZwpInputManagerV3 object
func NewZwpInputManagerV3(ctx *Context) *ZwpInputManagerV3 {
	ret := new(ZwpInputManagerV3)
	ctx.Register(ret)
	return ret
}
// Destroy Destroy the wp_text_input_manager
func (p *ZwpInputManagerV3) Destroy() (error) {
	
	return p.Context().SendRequest(p, 0)
}
// GetInput create a new text input object
func (p *ZwpInputManagerV3) GetInput(Seat *Seat) (*ZwpInputV3, error) {
	retId := NewZwpInputV3(p.Context())
	return retId, p.Context().SendRequest(p, 1, retId, Seat)
}
// Dispatch dispatches event for object ZwpInputManagerV3
func (p *ZwpInputManagerV3) Dispatch(event *Event) {
	switch event.Opcode {

	}
}
