/* Generated by wayland-scanner 1.12.0 */

#ifndef WESTON_TEST_SERVER_PROTOCOL_H
#define WESTON_TEST_SERVER_PROTOCOL_H

#include <stdint.h>
#include <stddef.h>
#include "wayland-server.h"

#ifdef  __cplusplus
extern "C" {
#endif

struct wl_client;
struct wl_resource;

/**
 * @page page_weston_test The weston_test protocol
 * @section page_ifaces_weston_test Interfaces
 * - @subpage page_iface_weston_test - weston internal testing
 * - @subpage page_iface_weston_test_runner - weston internal testing
 * @section page_copyright_weston_test Copyright
 * <pre>
 *
 * Copyright © 2012 Intel Corporation
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice (including the next
 * paragraph) shall be included in all copies or substantial portions of the
 * Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
 * THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 * </pre>
 */
struct weston_test;
struct weston_test_runner;
struct wl_buffer;
struct wl_output;
struct wl_surface;

/**
 * @page page_iface_weston_test weston_test
 * @section page_iface_weston_test_desc Description
 *
 * Internal testing facilities for the weston compositor.
 *
 * It can't be stressed enough that these should never ever be used
 * outside of running weston's tests.  The weston-test.so module should
 * never be installed.
 *
 * These requests may allow clients to do very bad things.
 * @section page_iface_weston_test_api API
 * See @ref iface_weston_test.
 */
/**
 * @defgroup iface_weston_test The weston_test interface
 *
 * Internal testing facilities for the weston compositor.
 *
 * It can't be stressed enough that these should never ever be used
 * outside of running weston's tests.  The weston-test.so module should
 * never be installed.
 *
 * These requests may allow clients to do very bad things.
 */
extern const struct wl_interface weston_test_interface;
/**
 * @page page_iface_weston_test_runner weston_test_runner
 * @section page_iface_weston_test_runner_desc Description
 *
 * This is a global singleton interface for Weston internal tests.
 *
 * This interface allows a test client to trigger compositor-side
 * test procedures. This is useful for cases, where the actual tests
 * are in compositor plugins, but they also require the presence of
 * a particular client.
 *
 * This interface is implemented by the compositor plugins containing
 * the testing code.
 *
 * A test client starts a test with the "run" request. It must not send
 * another "run" request until receiving the "finished" event. If the
 * compositor-side test succeeds, the "finished" event is sent. If the
 * compositor-side test fails, the compositor should send the protocol
 * error "test_failed", but it may also exit with an error (e.g. SEGV).
 *
 * Unknown test name will raise "unknown_test" protocol error.
 * @section page_iface_weston_test_runner_api API
 * See @ref iface_weston_test_runner.
 */
/**
 * @defgroup iface_weston_test_runner The weston_test_runner interface
 *
 * This is a global singleton interface for Weston internal tests.
 *
 * This interface allows a test client to trigger compositor-side
 * test procedures. This is useful for cases, where the actual tests
 * are in compositor plugins, but they also require the presence of
 * a particular client.
 *
 * This interface is implemented by the compositor plugins containing
 * the testing code.
 *
 * A test client starts a test with the "run" request. It must not send
 * another "run" request until receiving the "finished" event. If the
 * compositor-side test succeeds, the "finished" event is sent. If the
 * compositor-side test fails, the compositor should send the protocol
 * error "test_failed", but it may also exit with an error (e.g. SEGV).
 *
 * Unknown test name will raise "unknown_test" protocol error.
 */
extern const struct wl_interface weston_test_runner_interface;

/**
 * @ingroup iface_weston_test
 * @struct weston_test_interface
 */
struct weston_test_interface {
	/**
	 */
	void (*move_surface)(struct wl_client *client,
			     struct wl_resource *resource,
			     struct wl_resource *surface,
			     int32_t x,
			     int32_t y);
	/**
	 */
	void (*move_pointer)(struct wl_client *client,
			     struct wl_resource *resource,
			     int32_t x,
			     int32_t y);
	/**
	 */
	void (*send_button)(struct wl_client *client,
			    struct wl_resource *resource,
			    int32_t button,
			    uint32_t state);
	/**
	 */
	void (*activate_surface)(struct wl_client *client,
				 struct wl_resource *resource,
				 struct wl_resource *surface);
	/**
	 */
	void (*send_key)(struct wl_client *client,
			 struct wl_resource *resource,
			 uint32_t key,
			 uint32_t state);
	/**
	 */
	void (*device_release)(struct wl_client *client,
			       struct wl_resource *resource,
			       const char *device);
	/**
	 */
	void (*device_add)(struct wl_client *client,
			   struct wl_resource *resource,
			   const char *device);
	/**
	 */
	void (*get_n_egl_buffers)(struct wl_client *client,
				  struct wl_resource *resource);
	/**
	 * records current screen image
	 *
	 * Records an image of what is currently displayed on a given
	 * display output, returning the image as an event.
	 * @param output output to capture from
	 * @param buffer buffer for returning screenshots to the test client
	 */
	void (*capture_screenshot)(struct wl_client *client,
				   struct wl_resource *resource,
				   struct wl_resource *output,
				   struct wl_resource *buffer);
};

#define WESTON_TEST_POINTER_POSITION 0
#define WESTON_TEST_N_EGL_BUFFERS 1
#define WESTON_TEST_CAPTURE_SCREENSHOT_DONE 2

/**
 * @ingroup iface_weston_test
 */
#define WESTON_TEST_POINTER_POSITION_SINCE_VERSION 1
/**
 * @ingroup iface_weston_test
 */
#define WESTON_TEST_N_EGL_BUFFERS_SINCE_VERSION 1
/**
 * @ingroup iface_weston_test
 */
#define WESTON_TEST_CAPTURE_SCREENSHOT_DONE_SINCE_VERSION 1

/**
 * @ingroup iface_weston_test
 */
#define WESTON_TEST_MOVE_SURFACE_SINCE_VERSION 1
/**
 * @ingroup iface_weston_test
 */
#define WESTON_TEST_MOVE_POINTER_SINCE_VERSION 1
/**
 * @ingroup iface_weston_test
 */
#define WESTON_TEST_SEND_BUTTON_SINCE_VERSION 1
/**
 * @ingroup iface_weston_test
 */
#define WESTON_TEST_ACTIVATE_SURFACE_SINCE_VERSION 1
/**
 * @ingroup iface_weston_test
 */
#define WESTON_TEST_SEND_KEY_SINCE_VERSION 1
/**
 * @ingroup iface_weston_test
 */
#define WESTON_TEST_DEVICE_RELEASE_SINCE_VERSION 1
/**
 * @ingroup iface_weston_test
 */
#define WESTON_TEST_DEVICE_ADD_SINCE_VERSION 1
/**
 * @ingroup iface_weston_test
 */
#define WESTON_TEST_GET_N_EGL_BUFFERS_SINCE_VERSION 1
/**
 * @ingroup iface_weston_test
 */
#define WESTON_TEST_CAPTURE_SCREENSHOT_SINCE_VERSION 1

/**
 * @ingroup iface_weston_test
 * Sends an pointer_position event to the client owning the resource.
 * @param resource_ The client's resource
 */
static inline void
weston_test_send_pointer_position(struct wl_resource *resource_, wl_fixed_t x, wl_fixed_t y)
{
	wl_resource_post_event(resource_, WESTON_TEST_POINTER_POSITION, x, y);
}

/**
 * @ingroup iface_weston_test
 * Sends an n_egl_buffers event to the client owning the resource.
 * @param resource_ The client's resource
 */
static inline void
weston_test_send_n_egl_buffers(struct wl_resource *resource_, uint32_t n)
{
	wl_resource_post_event(resource_, WESTON_TEST_N_EGL_BUFFERS, n);
}

/**
 * @ingroup iface_weston_test
 * Sends an capture_screenshot_done event to the client owning the resource.
 * @param resource_ The client's resource
 */
static inline void
weston_test_send_capture_screenshot_done(struct wl_resource *resource_)
{
	wl_resource_post_event(resource_, WESTON_TEST_CAPTURE_SCREENSHOT_DONE);
}

#ifndef WESTON_TEST_RUNNER_ERROR_ENUM
#define WESTON_TEST_RUNNER_ERROR_ENUM
enum weston_test_runner_error {
	/**
	 * compositor test failed
	 */
	WESTON_TEST_RUNNER_ERROR_TEST_FAILED = 0,
	/**
	 * unrecognized test name
	 */
	WESTON_TEST_RUNNER_ERROR_UNKNOWN_TEST = 1,
};
#endif /* WESTON_TEST_RUNNER_ERROR_ENUM */

/**
 * @ingroup iface_weston_test_runner
 * @struct weston_test_runner_interface
 */
struct weston_test_runner_interface {
	/**
	 */
	void (*destroy)(struct wl_client *client,
			struct wl_resource *resource);
	/**
	 */
	void (*run)(struct wl_client *client,
		    struct wl_resource *resource,
		    const char *test_name);
};

#define WESTON_TEST_RUNNER_FINISHED 0

/**
 * @ingroup iface_weston_test_runner
 */
#define WESTON_TEST_RUNNER_FINISHED_SINCE_VERSION 1

/**
 * @ingroup iface_weston_test_runner
 */
#define WESTON_TEST_RUNNER_DESTROY_SINCE_VERSION 1
/**
 * @ingroup iface_weston_test_runner
 */
#define WESTON_TEST_RUNNER_RUN_SINCE_VERSION 1

/**
 * @ingroup iface_weston_test_runner
 * Sends an finished event to the client owning the resource.
 * @param resource_ The client's resource
 */
static inline void
weston_test_runner_send_finished(struct wl_resource *resource_)
{
	wl_resource_post_event(resource_, WESTON_TEST_RUNNER_FINISHED);
}

#ifdef  __cplusplus
}
#endif

#endif
