// This file is autogenerated from: viewporter.xml
// Do not edit

// Package viewporter implements the viewporter protocol
package viewporter

import ()

// WpErrorViewportExists
const WpErrorViewportExists = 0

// WpViewportErrorBadValue
const WpViewportErrorBadValue = 0

// WpViewportErrorBadSize
const WpViewportErrorBadSize = 1

// WpViewportErrorOutOfBuffer
const WpViewportErrorOutOfBuffer = 2

// WpViewportErrorNoSurface
const WpViewportErrorNoSurface = 3

// WpViewporter
type WpViewporter struct {
	BaseProxy
}

// NewWpViewporter is a constructor for the WpViewporter object
func NewWpViewporter(ctx *Context) *WpViewporter {
	ret := new(WpViewporter)
	ctx.Register(ret)
	return ret
}

// Destroy
func (p *WpViewporter) Destroy() error {

	return p.Context().SendRequest(p, 0)
}

// GetViewport
func (p *WpViewporter) GetViewport(Surface *Surface) (*WpViewport, error) {
	retId := NewWpViewport(p.Context())
	return retId, p.Context().SendRequest(p, 1, retId, Surface)
}

// Dispatch dispatches event for object WpViewporter
func (p *WpViewporter) Dispatch(event *Event) {
	switch event.Opcode {

	}
}

// WpViewport
type WpViewport struct {
	BaseProxy
}

// NewWpViewport is a constructor for the WpViewport object
func NewWpViewport(ctx *Context) *WpViewport {
	ret := new(WpViewport)
	ctx.Register(ret)
	return ret
}

// Destroy
func (p *WpViewport) Destroy() error {

	return p.Context().SendRequest(p, 0)
}

// SetSource
func (p *WpViewport) SetSource(X float32, Y float32, Width float32, Height float32) error {

	return p.Context().SendRequest(p, 1, X, Y, Width, Height)
}

// SetDestination
func (p *WpViewport) SetDestination(Width int32, Height int32) error {

	return p.Context().SendRequest(p, 2, Width, Height)
}

// Dispatch dispatches event for object WpViewport
func (p *WpViewport) Dispatch(event *Event) {
	switch event.Opcode {

	}
}
