// This file is autogenerated from: fractional-scale-v1.xml
// Do not edit

// Package fractional implements the fractional_scale_v1 protocol
package fractional

import (
	"sync"
)

// WpScaleManagerV1ErrorScaleExists
const WpScaleManagerV1ErrorScaleExists = 0

// WpScaleManagerV1
type WpScaleManagerV1 struct {
	BaseProxy
}

// NewWpScaleManagerV1 is a constructor for the WpScaleManagerV1 object
func NewWpScaleManagerV1(ctx *Context) *WpScaleManagerV1 {
	ret := new(WpScaleManagerV1)
	ctx.Register(ret)
	return ret
}

// Destroy
func (p *WpScaleManagerV1) Destroy() error {

	return p.Context().SendRequest(p, 0)
}

// GetScale
func (p *WpScaleManagerV1) GetScale(Surface *Surface) (*WpScaleV1, error) {
	retId := NewWpScaleV1(p.Context())
	return retId, p.Context().SendRequest(p, 1, retId, Surface)
}

// Dispatch dispatches event for object WpScaleManagerV1
func (p *WpScaleManagerV1) Dispatch(event *Event) {
	switch event.Opcode {

	}
}

// WpScaleV1
type WpScaleV1 struct {
	BaseProxy
	mu                              sync.RWMutex
	privateWpScaleV1PreferredScales map[WpScaleV1PreferredScaleHandler]struct{}
}

// initWpScaleV1 initializes the WpScaleV1 object's handler maps
func (ret *WpScaleV1) initWpScaleV1() {
	ret.privateWpScaleV1PreferredScales = make(map[WpScaleV1PreferredScaleHandler]struct{})
}

// NewWpScaleV1 is a constructor for the WpScaleV1 object
func NewWpScaleV1(ctx *Context) *WpScaleV1 {
	ret := new(WpScaleV1)
	ret.initWpScaleV1()
	ctx.Register(ret)
	return ret
}

// Destroy
func (p *WpScaleV1) Destroy() error {

	return p.Context().SendRequest(p, 0)
}

// Dispatch dispatches event for object WpScaleV1
func (p *WpScaleV1) Dispatch(event *Event) {
	switch event.Opcode {
	case 0:
		if len(p.privateWpScaleV1PreferredScales) > 0 {
			ev := WpScaleV1PreferredScaleEvent{}
			ev.Scale = event.Uint32()
			p.mu.RLock()
			for h := range p.privateWpScaleV1PreferredScales {
				h.HandleWpScaleV1PreferredScale(ev)
			}
			p.mu.RUnlock()
		}

	}
}

// WpScaleV1PreferredScaleEvent is the
type WpScaleV1PreferredScaleEvent struct {
	// Scale is the
	Scale uint32
}

// WpScaleV1PreferredScaleHandler is the handler interface for WpScaleV1PreferredScaleEvent
type WpScaleV1PreferredScaleHandler interface {
	HandleWpScaleV1PreferredScale(WpScaleV1PreferredScaleEvent)
}

// AddPreferredScaleHandler adds the PreferredScale handler
func (p *WpScaleV1) AddPreferredScaleHandler(h WpScaleV1PreferredScaleHandler) {
	if h != nil {
		p.mu.Lock()
		p.privateWpScaleV1PreferredScales[h] = struct{}{}
		p.mu.Unlock()
	}
}

// RemovePreferredScaleHandler removes the PreferredScale handler
func (p *WpScaleV1) RemovePreferredScaleHandler(h WpScaleV1PreferredScaleHandler) {
	p.mu.Lock()
	defer p.mu.Unlock()

	delete(p.privateWpScaleV1PreferredScales, h)
}
