package wl

const POINTER_ENTER_SINCE_VERSION = 1
const POINTER_LEAVE_SINCE_VERSION = 1
const POINTER_MOTION_SINCE_VERSION = 1
const POINTER_BUTTON_SINCE_VERSION = 1
const POINTER_AXIS_SINCE_VERSION = 1
const POINTER_FRAME_SINCE_VERSION = 5
const POINTER_AXIS_SOURCE_SINCE_VERSION = 5
const POINTER_AXIS_STOP_SINCE_VERSION = 5
const POINTER_AXIS_DISCRETE_SINCE_VERSION = 5
const POINTER_SET_CURSOR_SINCE_VERSION = 1
const POINTER_RELEASE_SINCE_VERSION = 3
