// This file is autogenerated from: linux-dmabuf-v1.xml
// Do not edit

// Package linux implements the linux_dmabuf_v1 protocol
package linux

import (
	"sync"

)
// ZwpBufferParamsV1ErrorAlreadyUsed means the dmabuf_batch object has already been used to create a wl_buffer
const ZwpBufferParamsV1ErrorAlreadyUsed = 0

// ZwpBufferParamsV1ErrorPlaneIdx means plane index out of bounds
const ZwpBufferParamsV1ErrorPlaneIdx = 1

// ZwpBufferParamsV1ErrorPlaneSet means the plane index was already set
const ZwpBufferParamsV1ErrorPlaneSet = 2

// ZwpBufferParamsV1ErrorIncomplete means missing or too many planes to create a buffer
const ZwpBufferParamsV1ErrorIncomplete = 3

// ZwpBufferParamsV1ErrorInvalidFormat means format not supported
const ZwpBufferParamsV1ErrorInvalidFormat = 4

// ZwpBufferParamsV1ErrorInvalidDimensions means invalid width or height
const ZwpBufferParamsV1ErrorInvalidDimensions = 5

// ZwpBufferParamsV1ErrorOutOfBounds means offset + stride * height goes out of dmabuf bounds
const ZwpBufferParamsV1ErrorOutOfBounds = 6

// ZwpBufferParamsV1ErrorInvalidWlBuffer means invalid wl_buffer resulted from importing dmabufs via the create_immed request on given buffer_params
const ZwpBufferParamsV1ErrorInvalidWlBuffer = 7

// ZwpBufferParamsV1FlagsYInvert means contents are y-inverted
const ZwpBufferParamsV1FlagsYInvert = 1

// ZwpBufferParamsV1FlagsInterlaced means content is interlaced
const ZwpBufferParamsV1FlagsInterlaced = 2

// ZwpBufferParamsV1FlagsBottomFirst means bottom field first
const ZwpBufferParamsV1FlagsBottomFirst = 4

// ZwpDmabufFeedbackV1TrancheFlagsScanout means direct scan-out tranche
const ZwpDmabufFeedbackV1TrancheFlagsScanout = 1

// ZwpDmabufV1 factory for creating dmabuf-based wl_buffers
type ZwpDmabufV1 struct {
	BaseProxy
	mu sync.RWMutex
	privateZwpDmabufV1Formats map[ZwpDmabufV1FormatHandler]struct{}
	privateZwpDmabufV1Modifiers map[ZwpDmabufV1ModifierHandler]struct{}
}
// initZwpDmabufV1 initializes the ZwpDmabufV1 object's handler maps
func (ret *ZwpDmabufV1) initZwpDmabufV1() {
	ret.privateZwpDmabufV1Formats = make(map[ZwpDmabufV1FormatHandler]struct{})
	ret.privateZwpDmabufV1Modifiers = make(map[ZwpDmabufV1ModifierHandler]struct{})
}
// NewZwpDmabufV1 is a constructor for the ZwpDmabufV1 object
func NewZwpDmabufV1(ctx *Context) *ZwpDmabufV1 {
	ret := new(ZwpDmabufV1)
	ret.initZwpDmabufV1()
	ctx.Register(ret)
	return ret
}
// Destroy unbind the factory
func (p *ZwpDmabufV1) Destroy() (error) {
	
	return p.Context().SendRequest(p, 0)
}
// CreateParams create a temporary object for buffer parameters
func (p *ZwpDmabufV1) CreateParams() (*ZwpBufferParamsV1, error) {
	retParamsId := NewZwpBufferParamsV1(p.Context())
	return retParamsId, p.Context().SendRequest(p, 1, retParamsId)
}
// GetDefaultFeedback get default feedback
func (p *ZwpDmabufV1) GetDefaultFeedback() (*ZwpDmabufFeedbackV1, error) {
	retId := NewZwpDmabufFeedbackV1(p.Context())
	return retId, p.Context().SendRequest(p, 2, retId)
}
// GetSurfaceFeedback get feedback for a surface
func (p *ZwpDmabufV1) GetSurfaceFeedback(Surface *Surface) (*ZwpDmabufFeedbackV1, error) {
	retId := NewZwpDmabufFeedbackV1(p.Context())
	return retId, p.Context().SendRequest(p, 3, retId, Surface)
}
// Dispatch dispatches event for object ZwpDmabufV1
func (p *ZwpDmabufV1) Dispatch(event *Event) {
	switch event.Opcode {
	case 0:
		if len(p.privateZwpDmabufV1Formats) > 0 {
			ev := ZwpDmabufV1FormatEvent{}
			ev.Format = event.Uint32()
			p.mu.RLock()
			for h := range p.privateZwpDmabufV1Formats {
				h.HandleZwpDmabufV1Format(ev)
			}
			p.mu.RUnlock()
		}
	case 1:
		if len(p.privateZwpDmabufV1Modifiers) > 0 {
			ev := ZwpDmabufV1ModifierEvent{}
			ev.Format = event.Uint32()
			ev.ModifierHi = event.Uint32()
			ev.ModifierLo = event.Uint32()
			p.mu.RLock()
			for h := range p.privateZwpDmabufV1Modifiers {
				h.HandleZwpDmabufV1Modifier(ev)
			}
			p.mu.RUnlock()
		}

	}
}
// ZwpDmabufV1FormatEvent is the supported buffer format
type ZwpDmabufV1FormatEvent struct {
	// Format is the DRM_FORMAT code
	Format uint32

}
// ZwpDmabufV1ModifierEvent is the supported buffer format modifier
type ZwpDmabufV1ModifierEvent struct {
	// Format is the DRM_FORMAT code
	Format uint32
	// ModifierHi is the high 32 bits of layout modifier
	ModifierHi uint32
	// ModifierLo is the low 32 bits of layout modifier
	ModifierLo uint32

}
// ZwpDmabufV1FormatHandler is the handler interface for ZwpDmabufV1FormatEvent
type ZwpDmabufV1FormatHandler interface {
	HandleZwpDmabufV1Format(ZwpDmabufV1FormatEvent)
}

// AddFormatHandler adds the Format handler
func (p *ZwpDmabufV1) AddFormatHandler(h ZwpDmabufV1FormatHandler) {
	if h != nil {
		p.mu.Lock()
		p.privateZwpDmabufV1Formats[h] = struct{}{}
		p.mu.Unlock()
	}
}

// RemoveFormatHandler removes the Format handler
func (p *ZwpDmabufV1) RemoveFormatHandler(h ZwpDmabufV1FormatHandler) {
	p.mu.Lock()
	defer p.mu.Unlock()

	delete (p.privateZwpDmabufV1Formats, h)
}
// ZwpDmabufV1ModifierHandler is the handler interface for ZwpDmabufV1ModifierEvent
type ZwpDmabufV1ModifierHandler interface {
	HandleZwpDmabufV1Modifier(ZwpDmabufV1ModifierEvent)
}

// AddModifierHandler adds the Modifier handler
func (p *ZwpDmabufV1) AddModifierHandler(h ZwpDmabufV1ModifierHandler) {
	if h != nil {
		p.mu.Lock()
		p.privateZwpDmabufV1Modifiers[h] = struct{}{}
		p.mu.Unlock()
	}
}

// RemoveModifierHandler removes the Modifier handler
func (p *ZwpDmabufV1) RemoveModifierHandler(h ZwpDmabufV1ModifierHandler) {
	p.mu.Lock()
	defer p.mu.Unlock()

	delete (p.privateZwpDmabufV1Modifiers, h)
}
// ZwpBufferParamsV1 parameters for creating a dmabuf-based wl_buffer
type ZwpBufferParamsV1 struct {
	BaseProxy
	mu sync.RWMutex
	privateZwpBufferParamsV1Createds map[ZwpBufferParamsV1CreatedHandler]struct{}
	privateZwpBufferParamsV1Faileds map[ZwpBufferParamsV1FailedHandler]struct{}
}
// initZwpBufferParamsV1 initializes the ZwpBufferParamsV1 object's handler maps
func (ret *ZwpBufferParamsV1) initZwpBufferParamsV1() {
	ret.privateZwpBufferParamsV1Createds = make(map[ZwpBufferParamsV1CreatedHandler]struct{})
	ret.privateZwpBufferParamsV1Faileds = make(map[ZwpBufferParamsV1FailedHandler]struct{})
}
// NewZwpBufferParamsV1 is a constructor for the ZwpBufferParamsV1 object
func NewZwpBufferParamsV1(ctx *Context) *ZwpBufferParamsV1 {
	ret := new(ZwpBufferParamsV1)
	ret.initZwpBufferParamsV1()
	ctx.Register(ret)
	return ret
}
// Destroy delete this object, used or not
func (p *ZwpBufferParamsV1) Destroy() (error) {
	
	return p.Context().SendRequest(p, 0)
}
// Add add a dmabuf to the temporary set
func (p *ZwpBufferParamsV1) Add(Fd uintptr, PlaneIdx uint32, Offset uint32, Stride uint32, ModifierHi uint32, ModifierLo uint32) (error) {
	
	return p.Context().SendRequest(p, 1, Fd, PlaneIdx, Offset, Stride, ModifierHi, ModifierLo)
}
// Create create a wl_buffer from the given dmabufs
func (p *ZwpBufferParamsV1) Create(Width int32, Height int32, Format uint32, Flags uint32) (error) {
	
	return p.Context().SendRequest(p, 2, Width, Height, Format, Flags)
}
// CreateImmed immediately create a wl_buffer from the given dmabufs
func (p *ZwpBufferParamsV1) CreateImmed(Width int32, Height int32, Format uint32, Flags uint32) (*Buffer, error) {
	retBufferId := NewBuffer(p.Context())
	return retBufferId, p.Context().SendRequest(p, 3, retBufferId, Width, Height, Format, Flags)
}
// Dispatch dispatches event for object ZwpBufferParamsV1
func (p *ZwpBufferParamsV1) Dispatch(event *Event) {
	switch event.Opcode {
	case 0:
		if len(p.privateZwpBufferParamsV1Createds) > 0 {
			ev := ZwpBufferParamsV1CreatedEvent{}
			ev.Buffer = func() *Buffer { ret := new(Buffer); ret.initBuffer(); return event.NewId(ret, p.Context()).(*Buffer) }()
			p.mu.RLock()
			for h := range p.privateZwpBufferParamsV1Createds {
				h.HandleZwpBufferParamsV1Created(ev)
			}
			p.mu.RUnlock()
		}
	case 1:
		if len(p.privateZwpBufferParamsV1Faileds) > 0 {
			ev := ZwpBufferParamsV1FailedEvent{}
			p.mu.RLock()
			for h := range p.privateZwpBufferParamsV1Faileds {
				h.HandleZwpBufferParamsV1Failed(ev)
			}
			p.mu.RUnlock()
		}

	}
}
// ZwpBufferParamsV1CreatedEvent is the buffer creation succeeded
type ZwpBufferParamsV1CreatedEvent struct {
	// Buffer is the the newly created wl_buffer
	Buffer *Buffer

}
// ZwpBufferParamsV1FailedEvent is the buffer creation failed
type ZwpBufferParamsV1FailedEvent struct {

}
// ZwpBufferParamsV1CreatedHandler is the handler interface for ZwpBufferParamsV1CreatedEvent
type ZwpBufferParamsV1CreatedHandler interface {
	HandleZwpBufferParamsV1Created(ZwpBufferParamsV1CreatedEvent)
}

// AddCreatedHandler adds the Created handler
func (p *ZwpBufferParamsV1) AddCreatedHandler(h ZwpBufferParamsV1CreatedHandler) {
	if h != nil {
		p.mu.Lock()
		p.privateZwpBufferParamsV1Createds[h] = struct{}{}
		p.mu.Unlock()
	}
}

// RemoveCreatedHandler removes the Created handler
func (p *ZwpBufferParamsV1) RemoveCreatedHandler(h ZwpBufferParamsV1CreatedHandler) {
	p.mu.Lock()
	defer p.mu.Unlock()

	delete (p.privateZwpBufferParamsV1Createds, h)
}
// ZwpBufferParamsV1FailedHandler is the handler interface for ZwpBufferParamsV1FailedEvent
type ZwpBufferParamsV1FailedHandler interface {
	HandleZwpBufferParamsV1Failed(ZwpBufferParamsV1FailedEvent)
}

// AddFailedHandler adds the Failed handler
func (p *ZwpBufferParamsV1) AddFailedHandler(h ZwpBufferParamsV1FailedHandler) {
	if h != nil {
		p.mu.Lock()
		p.privateZwpBufferParamsV1Faileds[h] = struct{}{}
		p.mu.Unlock()
	}
}

// RemoveFailedHandler removes the Failed handler
func (p *ZwpBufferParamsV1) RemoveFailedHandler(h ZwpBufferParamsV1FailedHandler) {
	p.mu.Lock()
	defer p.mu.Unlock()

	delete (p.privateZwpBufferParamsV1Faileds, h)
}
// ZwpDmabufFeedbackV1 dmabuf feedback
type ZwpDmabufFeedbackV1 struct {
	BaseProxy
	mu sync.RWMutex
	privateZwpDmabufFeedbackV1Dones map[ZwpDmabufFeedbackV1DoneHandler]struct{}
	privateZwpDmabufFeedbackV1FormatTables map[ZwpDmabufFeedbackV1FormatTableHandler]struct{}
	privateZwpDmabufFeedbackV1MainDevices map[ZwpDmabufFeedbackV1MainDeviceHandler]struct{}
	privateZwpDmabufFeedbackV1TrancheDones map[ZwpDmabufFeedbackV1TrancheDoneHandler]struct{}
	privateZwpDmabufFeedbackV1TrancheTargetDevices map[ZwpDmabufFeedbackV1TrancheTargetDeviceHandler]struct{}
	privateZwpDmabufFeedbackV1TrancheFormatss map[ZwpDmabufFeedbackV1TrancheFormatsHandler]struct{}
	privateZwpDmabufFeedbackV1TrancheFlagss map[ZwpDmabufFeedbackV1TrancheFlagsHandler]struct{}
}
// initZwpDmabufFeedbackV1 initializes the ZwpDmabufFeedbackV1 object's handler maps
func (ret *ZwpDmabufFeedbackV1) initZwpDmabufFeedbackV1() {
	ret.privateZwpDmabufFeedbackV1Dones = make(map[ZwpDmabufFeedbackV1DoneHandler]struct{})
	ret.privateZwpDmabufFeedbackV1FormatTables = make(map[ZwpDmabufFeedbackV1FormatTableHandler]struct{})
	ret.privateZwpDmabufFeedbackV1MainDevices = make(map[ZwpDmabufFeedbackV1MainDeviceHandler]struct{})
	ret.privateZwpDmabufFeedbackV1TrancheDones = make(map[ZwpDmabufFeedbackV1TrancheDoneHandler]struct{})
	ret.privateZwpDmabufFeedbackV1TrancheTargetDevices = make(map[ZwpDmabufFeedbackV1TrancheTargetDeviceHandler]struct{})
	ret.privateZwpDmabufFeedbackV1TrancheFormatss = make(map[ZwpDmabufFeedbackV1TrancheFormatsHandler]struct{})
	ret.privateZwpDmabufFeedbackV1TrancheFlagss = make(map[ZwpDmabufFeedbackV1TrancheFlagsHandler]struct{})
}
// NewZwpDmabufFeedbackV1 is a constructor for the ZwpDmabufFeedbackV1 object
func NewZwpDmabufFeedbackV1(ctx *Context) *ZwpDmabufFeedbackV1 {
	ret := new(ZwpDmabufFeedbackV1)
	ret.initZwpDmabufFeedbackV1()
	ctx.Register(ret)
	return ret
}
// Destroy destroy the feedback object
func (p *ZwpDmabufFeedbackV1) Destroy() (error) {
	
	return p.Context().SendRequest(p, 0)
}
// Dispatch dispatches event for object ZwpDmabufFeedbackV1
func (p *ZwpDmabufFeedbackV1) Dispatch(event *Event) {
	switch event.Opcode {
	case 0:
		if len(p.privateZwpDmabufFeedbackV1Dones) > 0 {
			ev := ZwpDmabufFeedbackV1DoneEvent{}
			p.mu.RLock()
			for h := range p.privateZwpDmabufFeedbackV1Dones {
				h.HandleZwpDmabufFeedbackV1Done(ev)
			}
			p.mu.RUnlock()
		}
	case 1:
		if len(p.privateZwpDmabufFeedbackV1FormatTables) > 0 {
			ev := ZwpDmabufFeedbackV1FormatTableEvent{}
			ev.Fd, ev.FdError = event.FD()
			ev.Size = event.Uint32()
			p.mu.RLock()
			for h := range p.privateZwpDmabufFeedbackV1FormatTables {
				h.HandleZwpDmabufFeedbackV1FormatTable(ev)
			}
			p.mu.RUnlock()
		}
	case 2:
		if len(p.privateZwpDmabufFeedbackV1MainDevices) > 0 {
			ev := ZwpDmabufFeedbackV1MainDeviceEvent{}
			ev.Device = event.Array()
			p.mu.RLock()
			for h := range p.privateZwpDmabufFeedbackV1MainDevices {
				h.HandleZwpDmabufFeedbackV1MainDevice(ev)
			}
			p.mu.RUnlock()
		}
	case 3:
		if len(p.privateZwpDmabufFeedbackV1TrancheDones) > 0 {
			ev := ZwpDmabufFeedbackV1TrancheDoneEvent{}
			p.mu.RLock()
			for h := range p.privateZwpDmabufFeedbackV1TrancheDones {
				h.HandleZwpDmabufFeedbackV1TrancheDone(ev)
			}
			p.mu.RUnlock()
		}
	case 4:
		if len(p.privateZwpDmabufFeedbackV1TrancheTargetDevices) > 0 {
			ev := ZwpDmabufFeedbackV1TrancheTargetDeviceEvent{}
			ev.Device = event.Array()
			p.mu.RLock()
			for h := range p.privateZwpDmabufFeedbackV1TrancheTargetDevices {
				h.HandleZwpDmabufFeedbackV1TrancheTargetDevice(ev)
			}
			p.mu.RUnlock()
		}
	case 5:
		if len(p.privateZwpDmabufFeedbackV1TrancheFormatss) > 0 {
			ev := ZwpDmabufFeedbackV1TrancheFormatsEvent{}
			ev.Indices = event.Array()
			p.mu.RLock()
			for h := range p.privateZwpDmabufFeedbackV1TrancheFormatss {
				h.HandleZwpDmabufFeedbackV1TrancheFormats(ev)
			}
			p.mu.RUnlock()
		}
	case 6:
		if len(p.privateZwpDmabufFeedbackV1TrancheFlagss) > 0 {
			ev := ZwpDmabufFeedbackV1TrancheFlagsEvent{}
			ev.Flags = event.Uint32()
			p.mu.RLock()
			for h := range p.privateZwpDmabufFeedbackV1TrancheFlagss {
				h.HandleZwpDmabufFeedbackV1TrancheFlags(ev)
			}
			p.mu.RUnlock()
		}

	}
}
// ZwpDmabufFeedbackV1DoneEvent is the all feedback has been sent
type ZwpDmabufFeedbackV1DoneEvent struct {

}
// ZwpDmabufFeedbackV1FormatTableEvent is the format and modifier table
type ZwpDmabufFeedbackV1FormatTableEvent struct {
	// Fd is the table file descriptor
	Fd uintptr
	// FdError is the table file descriptor (error)
	FdError error
	// Size is the table size, in bytes
	Size uint32

}
// ZwpDmabufFeedbackV1MainDeviceEvent is the preferred main device
type ZwpDmabufFeedbackV1MainDeviceEvent struct {
	// Device is the device dev_t value
	Device []int32

}
// ZwpDmabufFeedbackV1TrancheDoneEvent is the a preference tranche has been sent
type ZwpDmabufFeedbackV1TrancheDoneEvent struct {

}
// ZwpDmabufFeedbackV1TrancheTargetDeviceEvent is the target device
type ZwpDmabufFeedbackV1TrancheTargetDeviceEvent struct {
	// Device is the device dev_t value
	Device []int32

}
// ZwpDmabufFeedbackV1TrancheFormatsEvent is the supported buffer format modifier
type ZwpDmabufFeedbackV1TrancheFormatsEvent struct {
	// Indices is the array of 16-bit indexes
	Indices []int32

}
// ZwpDmabufFeedbackV1TrancheFlagsEvent is the tranche flags
type ZwpDmabufFeedbackV1TrancheFlagsEvent struct {
	// Flags is the tranche flags
	Flags uint32

}
// ZwpDmabufFeedbackV1DoneHandler is the handler interface for ZwpDmabufFeedbackV1DoneEvent
type ZwpDmabufFeedbackV1DoneHandler interface {
	HandleZwpDmabufFeedbackV1Done(ZwpDmabufFeedbackV1DoneEvent)
}

// AddDoneHandler adds the Done handler
func (p *ZwpDmabufFeedbackV1) AddDoneHandler(h ZwpDmabufFeedbackV1DoneHandler) {
	if h != nil {
		p.mu.Lock()
		p.privateZwpDmabufFeedbackV1Dones[h] = struct{}{}
		p.mu.Unlock()
	}
}

// RemoveDoneHandler removes the Done handler
func (p *ZwpDmabufFeedbackV1) RemoveDoneHandler(h ZwpDmabufFeedbackV1DoneHandler) {
	p.mu.Lock()
	defer p.mu.Unlock()

	delete (p.privateZwpDmabufFeedbackV1Dones, h)
}
// ZwpDmabufFeedbackV1FormatTableHandler is the handler interface for ZwpDmabufFeedbackV1FormatTableEvent
type ZwpDmabufFeedbackV1FormatTableHandler interface {
	HandleZwpDmabufFeedbackV1FormatTable(ZwpDmabufFeedbackV1FormatTableEvent)
}

// AddFormatTableHandler adds the FormatTable handler
func (p *ZwpDmabufFeedbackV1) AddFormatTableHandler(h ZwpDmabufFeedbackV1FormatTableHandler) {
	if h != nil {
		p.mu.Lock()
		p.privateZwpDmabufFeedbackV1FormatTables[h] = struct{}{}
		p.mu.Unlock()
	}
}

// RemoveFormatTableHandler removes the FormatTable handler
func (p *ZwpDmabufFeedbackV1) RemoveFormatTableHandler(h ZwpDmabufFeedbackV1FormatTableHandler) {
	p.mu.Lock()
	defer p.mu.Unlock()

	delete (p.privateZwpDmabufFeedbackV1FormatTables, h)
}
// ZwpDmabufFeedbackV1MainDeviceHandler is the handler interface for ZwpDmabufFeedbackV1MainDeviceEvent
type ZwpDmabufFeedbackV1MainDeviceHandler interface {
	HandleZwpDmabufFeedbackV1MainDevice(ZwpDmabufFeedbackV1MainDeviceEvent)
}

// AddMainDeviceHandler adds the MainDevice handler
func (p *ZwpDmabufFeedbackV1) AddMainDeviceHandler(h ZwpDmabufFeedbackV1MainDeviceHandler) {
	if h != nil {
		p.mu.Lock()
		p.privateZwpDmabufFeedbackV1MainDevices[h] = struct{}{}
		p.mu.Unlock()
	}
}

// RemoveMainDeviceHandler removes the MainDevice handler
func (p *ZwpDmabufFeedbackV1) RemoveMainDeviceHandler(h ZwpDmabufFeedbackV1MainDeviceHandler) {
	p.mu.Lock()
	defer p.mu.Unlock()

	delete (p.privateZwpDmabufFeedbackV1MainDevices, h)
}
// ZwpDmabufFeedbackV1TrancheDoneHandler is the handler interface for ZwpDmabufFeedbackV1TrancheDoneEvent
type ZwpDmabufFeedbackV1TrancheDoneHandler interface {
	HandleZwpDmabufFeedbackV1TrancheDone(ZwpDmabufFeedbackV1TrancheDoneEvent)
}

// AddTrancheDoneHandler adds the TrancheDone handler
func (p *ZwpDmabufFeedbackV1) AddTrancheDoneHandler(h ZwpDmabufFeedbackV1TrancheDoneHandler) {
	if h != nil {
		p.mu.Lock()
		p.privateZwpDmabufFeedbackV1TrancheDones[h] = struct{}{}
		p.mu.Unlock()
	}
}

// RemoveTrancheDoneHandler removes the TrancheDone handler
func (p *ZwpDmabufFeedbackV1) RemoveTrancheDoneHandler(h ZwpDmabufFeedbackV1TrancheDoneHandler) {
	p.mu.Lock()
	defer p.mu.Unlock()

	delete (p.privateZwpDmabufFeedbackV1TrancheDones, h)
}
// ZwpDmabufFeedbackV1TrancheTargetDeviceHandler is the handler interface for ZwpDmabufFeedbackV1TrancheTargetDeviceEvent
type ZwpDmabufFeedbackV1TrancheTargetDeviceHandler interface {
	HandleZwpDmabufFeedbackV1TrancheTargetDevice(ZwpDmabufFeedbackV1TrancheTargetDeviceEvent)
}

// AddTrancheTargetDeviceHandler adds the TrancheTargetDevice handler
func (p *ZwpDmabufFeedbackV1) AddTrancheTargetDeviceHandler(h ZwpDmabufFeedbackV1TrancheTargetDeviceHandler) {
	if h != nil {
		p.mu.Lock()
		p.privateZwpDmabufFeedbackV1TrancheTargetDevices[h] = struct{}{}
		p.mu.Unlock()
	}
}

// RemoveTrancheTargetDeviceHandler removes the TrancheTargetDevice handler
func (p *ZwpDmabufFeedbackV1) RemoveTrancheTargetDeviceHandler(h ZwpDmabufFeedbackV1TrancheTargetDeviceHandler) {
	p.mu.Lock()
	defer p.mu.Unlock()

	delete (p.privateZwpDmabufFeedbackV1TrancheTargetDevices, h)
}
// ZwpDmabufFeedbackV1TrancheFormatsHandler is the handler interface for ZwpDmabufFeedbackV1TrancheFormatsEvent
type ZwpDmabufFeedbackV1TrancheFormatsHandler interface {
	HandleZwpDmabufFeedbackV1TrancheFormats(ZwpDmabufFeedbackV1TrancheFormatsEvent)
}

// AddTrancheFormatsHandler adds the TrancheFormats handler
func (p *ZwpDmabufFeedbackV1) AddTrancheFormatsHandler(h ZwpDmabufFeedbackV1TrancheFormatsHandler) {
	if h != nil {
		p.mu.Lock()
		p.privateZwpDmabufFeedbackV1TrancheFormatss[h] = struct{}{}
		p.mu.Unlock()
	}
}

// RemoveTrancheFormatsHandler removes the TrancheFormats handler
func (p *ZwpDmabufFeedbackV1) RemoveTrancheFormatsHandler(h ZwpDmabufFeedbackV1TrancheFormatsHandler) {
	p.mu.Lock()
	defer p.mu.Unlock()

	delete (p.privateZwpDmabufFeedbackV1TrancheFormatss, h)
}
// ZwpDmabufFeedbackV1TrancheFlagsHandler is the handler interface for ZwpDmabufFeedbackV1TrancheFlagsEvent
type ZwpDmabufFeedbackV1TrancheFlagsHandler interface {
	HandleZwpDmabufFeedbackV1TrancheFlags(ZwpDmabufFeedbackV1TrancheFlagsEvent)
}

// AddTrancheFlagsHandler adds the TrancheFlags handler
func (p *ZwpDmabufFeedbackV1) AddTrancheFlagsHandler(h ZwpDmabufFeedbackV1TrancheFlagsHandler) {
	if h != nil {
		p.mu.Lock()
		p.privateZwpDmabufFeedbackV1TrancheFlagss[h] = struct{}{}
		p.mu.Unlock()
	}
}

// RemoveTrancheFlagsHandler removes the TrancheFlags handler
func (p *ZwpDmabufFeedbackV1) RemoveTrancheFlagsHandler(h ZwpDmabufFeedbackV1TrancheFlagsHandler) {
	p.mu.Lock()
	defer p.mu.Unlock()

	delete (p.privateZwpDmabufFeedbackV1TrancheFlagss, h)
}
