package main

import (
	"fmt"
	"strings"
)

type GoFile struct {
	Structs   []*GoStruct
	Constants []*GoConstant
	Name      string
	PkgName   string
	FileName  string
}

func (f *GoFile) AddStruct(s *GoStruct) {
	f.Structs = append(f.Structs, s)
}

func (f *GoFile) AddConstant(s *GoConstant) {
	f.Constants = append(f.Constants, s)
}

func (f *GoFile) IsNeedMutex() bool {
	for _, strct := range f.Structs {
		if strct.IsNeedMutex() {
			return true
		}
	}
	return false
}

func (f *GoFile) Serialize() string {
	var b strings.Builder
	b.WriteString("// This file is autogenerated from: ")
	b.WriteString(f.FileName)
	b.WriteString("\n// Do not edit\n\n")
	b.WriteString("// Package ")
	b.WriteString(f.PkgName)
	b.WriteString(" implements the ")
	b.WriteString(f.Name)
	b.WriteString(" protocol\n")
	b.WriteString(`package `)
	b.WriteString(f.PkgName)
	b.WriteString("\n\nimport (\n")
	if f.IsNeedMutex() {
		b.WriteString("\t\"sync\"\n")
	}
	b.WriteString("\n)\n")
	for _, k := range f.Constants {
		b.WriteString(k.Serialize())
	}
	for _, s := range f.Structs {
		b.WriteString(s.Serialize())
	}
	return b.String()
}

type GoDispatchMethod struct {
	Events []*GoEvent
}

func (m *GoDispatchMethod) Serialize(s *GoStruct) string {
	var b strings.Builder
	b.WriteString(`// Dispatch dispatches event for object `)
	b.WriteString(s.Name)
	b.WriteString(`
func (p *`)
	b.WriteString(s.Name)
	b.WriteString(`) Dispatch(event *Event) {
	switch event.Opcode {
`)
	for num, e := range m.Events {
		b.WriteString(e.SerializeCase(num))
	}
	b.WriteString("\n\t}\n}\n")
	return b.String()
}

type GoStruct struct {
	Name     string
	Comment  string
	Cons     GoConstructor
	Mets     []*GoMethod
	Events   []*GoEvent
	Handlers []*GoHandler
}

func (s *GoStruct) AddMethod(m *GoMethod) {
	s.Mets = append(s.Mets, m)
}

func (s *GoStruct) AddEvent(e *GoEvent) {
	s.Events = append(s.Events, e)
}

func (s *GoStruct) AddHandler(h *GoHandler) {
	s.Handlers = append(s.Handlers, h)
}

func (s *GoStruct) IsNeedMutex() bool {
	return len(s.Handlers) > 0
}

func (s *GoStruct) Serialize() string {
	var b strings.Builder
	b.WriteString(`// `)
	b.WriteString(s.Name)
	b.WriteString(` `)
	b.WriteString(s.Comment)
	b.WriteString(`
type `)
	b.WriteString(s.Name)
	b.WriteString(` struct {
	BaseProxy
`)
	if s.IsNeedMutex() {
		b.WriteString("\tmu sync.RWMutex\n")
	}
	for _, e := range s.Handlers {
		b.WriteString(e.SerializeAttr(s))
	}
	b.WriteString("}\n")
	b.WriteString(s.Cons.Serialize(s))
	for num, m := range s.Mets {
		b.WriteString(m.Serialize(num, s))
	}
	b.WriteString((&GoDispatchMethod{
		Events: s.Events,
	}).Serialize(s))
	for _, e := range s.Events {
		b.WriteString(e.Serialize())
	}
	for _, e := range s.Handlers {
		b.WriteString(e.Serialize(s))
	}
	return b.String()
}

type GoConstructor struct{}

func (*GoConstructor) Serialize(s *GoStruct) string {
	var b strings.Builder

	// Generate init method if there are handlers
	if len(s.Handlers) > 0 {
		b.WriteString(`// init`)
		b.WriteString(s.Name)
		b.WriteString(` initializes the `)
		b.WriteString(s.Name)
		b.WriteString(` object's handler maps
func (ret *`)
		b.WriteString(s.Name)
		b.WriteString(`) init`)
		b.WriteString(s.Name)
		b.WriteString(`() {
`)
		for _, h := range s.Handlers {
			b.WriteString("\tret.private")
			b.WriteString(s.Name)
			b.WriteString(h.Name)
			b.WriteString("s = make(map[")
			b.WriteString(s.Name)
			b.WriteString(h.Name)
			b.WriteString("Handler]struct{})\n")
		}
		b.WriteString("}\n")
	}

	b.WriteString(`// New`)
	b.WriteString(s.Name)
	b.WriteString(` is a constructor for the `)
	b.WriteString(s.Name)
	b.WriteString(` object
func New`)
	b.WriteString(s.Name)
	b.WriteString(`(ctx *Context) *`)
	b.WriteString(s.Name)
	b.WriteString(` {
	ret := new(`)
	b.WriteString(s.Name)
	b.WriteString(`)
`)
	// Initialize handler maps
	if len(s.Handlers) > 0 {
		b.WriteString("\tret.init")
		b.WriteString(s.Name)
		b.WriteString("()\n")
	}
	b.WriteString(`	ctx.Register(ret)
	return ret
}
`)
	return b.String()
}

type GoMethod struct {
	Name    string
	Comment string
	Args    []*GoArg
}

func (m *GoMethod) AddEventArg(s *GoArg, t *GoType) {
	s.Type = t
	m.Args = append(m.Args, s)
	if t.Type == "fd" {
		// Add the error arg for file descriptor here
		var s2 = GoArg{
			Name:    s.Name + "Error",
			Comment: s.Comment + " (error)",
			Type: &GoType{
				Type: "error",
			},
		}
		m.Args = append(m.Args, &s2)
	}
}

func (m *GoMethod) Serialize(num int, s *GoStruct) string {
	var b strings.Builder
	b.WriteString(`// `)
	b.WriteString(m.Name)
	b.WriteString(" ")
	b.WriteString(m.Comment)
	b.WriteString("\n" + `func (p *`)
	b.WriteString(s.Name)
	b.WriteString(`) `)
	b.WriteString(m.Name)
	b.WriteString(`(`)
	var first = true
	for _, arg := range m.Args {
		if arg.IsInput() {
			if first {
				first = false
			} else {
				b.WriteString(", ")
			}
			b.WriteString(arg.Name)
			b.WriteString(" ")
			b.WriteString(arg.Type.Serialize())
		}
	}
	b.WriteString(`) (`)
	for _, arg := range m.Args {
		if arg.IsOutput() {
			b.WriteString(arg.Type.Serialize())
			b.WriteString(", ")
		}
	}
	b.WriteString(`error) {
	`)
	for _, arg := range m.Args {
		if arg.IsOutput() {
			b.WriteString("ret")
			b.WriteString(arg.Name)
			b.WriteString(" := ")
			b.WriteString(arg.Type.SerializeNew())
		}
	}
	b.WriteString(`
	return `)

	for _, arg := range m.Args {
		if arg.IsOutput() {
			b.WriteString("ret")
			b.WriteString(arg.Name)
			b.WriteString(", ")
		}
	}

	b.WriteString(`p.Context().SendRequest(p, `)
	fmt.Fprintf(&b, "%d", num)
	for _, arg := range m.Args {
		if arg.IsOutput() {
			b.WriteString(", ret")
			b.WriteString(arg.Name)
		}
		if arg.IsInput() {
			b.WriteString(", ")
			b.WriteString(arg.Name)
		}
	}
	b.WriteString(")\n}\n")
	return b.String()
}

type GoEvent struct {
	Name    string
	Comment string
	Args    []*GoArg
	IsCb    bool
	IsPt    bool
	IsBf    bool
}

func (e *GoEvent) AddEventArg(s *GoArg, t *GoType) {
	s.Type = t
	e.Args = append(e.Args, s)
	if t.Type == "fd" {
		// Add the error arg for file descriptor here
		var s2 = GoArg{
			Name:    s.Name + "Error",
			Comment: s.Comment + " (error)",
			Type: &GoType{
				Type: "error",
			},
		}
		e.Args = append(e.Args, &s2)
	}
}

func (e *GoEvent) Serialize() string {
	var b strings.Builder
	b.WriteString(`// `)
	b.WriteString(e.Name)
	b.WriteString(`Event is the `)
	b.WriteString(e.Comment)
	b.WriteString(`
type `)
	b.WriteString(e.Name)
	b.WriteString(`Event struct {
`)
	for _, a := range e.Args {
		b.WriteString(a.Serialize())
	}
	if e.IsCb {
		b.WriteString("\tC *Callback")
	}
	if e.IsPt {
		b.WriteString("\tP *Pointer")
	}
	if e.IsBf {
		b.WriteString("\tB *Buffer")
	}
	b.WriteString("\n}\n")
	return b.String()
}

func (e *GoEvent) SerializeCase(num int) string {
	var b strings.Builder
	b.WriteString(`	case `)
	fmt.Fprintf(&b, "%d", num)
	b.WriteString(`:
		if len(p.private`)
	b.WriteString(e.Name)
	b.WriteString(`s) > 0 {
			ev := `)
	b.WriteString(e.Name)
	b.WriteString(`Event{}
`)
	if e.IsCb {
		b.WriteString("\t\t\tev.C = p\n")
	}
	if e.IsPt {
		b.WriteString("\t\t\tev.P = p\n")
	}
	if e.IsBf {
		b.WriteString("\t\t\tev.B = p\n")
	}
	for _, a := range e.Args {
		b.WriteString(a.SerializeCall())
	}
	b.WriteString(`			p.mu.RLock()
			for h := range p.private`)
	b.WriteString(e.Name)
	b.WriteString(`s {
				h.Handle`)
	b.WriteString(e.Name)
	b.WriteString(`(ev)
			}
			p.mu.RUnlock()
		}
`)
	return b.String()
}

type GoConstant struct {
	Name    string
	Value   string
	Comment string
}

func (c *GoConstant) Serialize() string {
	var means string
	if c.Comment != "" {
		means = " means "
	}

	return `// ` + c.Name + means + c.Comment + `
const ` + c.Name + ` = ` + c.Value + `

`
}

type GoArg struct {
	Name    string
	Comment string
	Type    *GoType
}

func (a *GoArg) IsCanError() bool {
	return a.Type.IsCanError()
}

func (a *GoArg) IsOutput() bool {
	return a.Type.IsOutput()
}
func (a *GoArg) IsInput() bool {
	return a.Type.IsInput()
}

func (a *GoArg) Serialize() string {
	return "\t// " + a.Name + " is the " + a.Comment + "\n\t" + a.Name + " " + a.Type.Serialize() + "\n"
}
func (a *GoArg) SerializeCall() string {
	call := a.Type.SerializeCall("event.")
	if call == "" {
		return ""
	}
	if a.IsCanError() {
		return "\t\t\tev." + a.Name + ", ev." + a.Name + "Error = " + call + "\n"
	}
	return "\t\t\tev." + a.Name + " = " + call + "\n"
}

type GoType struct {
	Type      string
	Interface string
}

func (a *GoType) SerializeNew() string {
	return "New" + a.Interface + "(p.Context())"
}
func (a *GoType) Serialize() string {
	switch a.Type {
	case "string":
		return "string"
	case "object":
		if a.Interface == "" {
			return "Proxy"
		}
		return "*" + a.Interface // pointer
	case "uint":
		return "uint32"
	case "int":
		return "int32"
	case "fd":
		return "uintptr"
	case "fixed":
		return "float32"
	case "array":
		return "[]int32"
	case "new_id":
		if a.Interface == "" {
			return "Proxy"
		}
		return "*" + a.Interface // pointer
	case "error":
		return "error"
	default:
		fmt.Println("Unknown type: " + a.Type)
		return "struct {} // unknown type"
	}
}
func (a *GoType) SerializeCall(eventDot string) string {
	switch a.Type {
	case "string":
		return eventDot + "String()"
	case "object":
		if a.Interface == "" {
			return eventDot + "Proxy(p.Context())"
		}
		return "SafeCast[*" + a.Interface + "](" + eventDot + "Proxy(p.Context()))"
	case "uint":
		return eventDot + "Uint32()"
	case "int":
		return eventDot + "Int32()"
	case "fd":
		return eventDot + "FD()"
	case "fixed":
		return eventDot + "Float32()"
	case "array":
		return eventDot + "Array()"
	case "new_id":
		return "func() *" + a.Interface + " { ret := new(" + a.Interface + "); ret.init" + a.Interface + "(); return " + eventDot + "NewId(ret, p.Context()).(*" + a.Interface + ") }()"
	case "error":
		return ""
	default:
		return ""
	}
}

func (a *GoType) IsCanError() bool {
	return a.Type == "fd"
}
func (a *GoType) isNewID() bool {
	return a.Type == "new_id" && a.Interface != ""
}
func (a *GoType) IsOutput() bool {
	return a.isNewID() && a.Type != "error"
}
func (a *GoType) IsInput() bool {
	return !a.isNewID() && a.Type != "error"
}

type GoHandler struct {
	Name string
}

func (h *GoHandler) Serialize(s *GoStruct) string {
	return `// ` + s.Name + h.Name + `Handler is the handler interface for ` + s.Name + h.Name + `Event
type ` + s.Name + h.Name + `Handler interface {
	Handle` + s.Name + h.Name + `(` + s.Name + h.Name + `Event)
}

// Add` + h.Name + `Handler adds the ` + h.Name + ` handler
func (p *` + s.Name + `) Add` + h.Name + `Handler(h ` + s.Name + h.Name + `Handler) {
	if h != nil {
		p.mu.Lock()
		p.private` + s.Name + h.Name + `s[h] = struct{}{}
		p.mu.Unlock()
	}
}

// Remove` + h.Name + `Handler removes the ` + h.Name + ` handler
func (p *` + s.Name + `) Remove` + h.Name + `Handler(h ` + s.Name + h.Name + `Handler) {
	p.mu.Lock()
	defer p.mu.Unlock()

	delete (p.private` + s.Name + h.Name + `s, h)
}
`
}
func (h *GoHandler) SerializeAttr(s *GoStruct) string {
	return "\t" + `private` + s.Name + h.Name + `s map[` + s.Name + h.Name + `Handler]struct{}` + "\n"
}
