// This file is autogenerated from: unstable/fullscreen-shell-v1/fullscreen-shell-unstable-v1.xml
// Do not edit

// Package fullscreen implements the fullscreen_shell_unstable_v1 protocol
package fullscreen

import (
	"sync"

)
// ZwpShellV1CapabilityArbitraryModes means compositor is capable of almost any output mode
const ZwpShellV1CapabilityArbitraryModes = 1

// ZwpShellV1CapabilityCursorPlane means compositor has a separate cursor plane
const ZwpShellV1CapabilityCursorPlane = 2

// ZwpShellV1PresentMethodDefault means no preference, apply default policy
const ZwpShellV1PresentMethodDefault = 0

// ZwpShellV1PresentMethodCenter means center the surface on the output
const ZwpShellV1PresentMethodCenter = 1

// ZwpShellV1PresentMethodZoom means scale the surface, preserving aspect ratio, to the largest size that will fit on the output
const ZwpShellV1PresentMethodZoom = 2

// ZwpShellV1PresentMethodZoomCrop means scale the surface, preserving aspect ratio, to fully fill the output cropping if needed
const ZwpShellV1PresentMethodZoomCrop = 3

// ZwpShellV1PresentMethodStretch means scale the surface to the size of the output ignoring aspect ratio
const ZwpShellV1PresentMethodStretch = 4

// ZwpShellV1ErrorInvalidMethod means present_method is not known
const ZwpShellV1ErrorInvalidMethod = 0

// ZwpShellV1ErrorRole means given wl_surface has another role
const ZwpShellV1ErrorRole = 1

// ZwpShellV1 displays a single surface per output
type ZwpShellV1 struct {
	BaseProxy
	mu sync.RWMutex
	privateZwpShellV1Capabilitys map[ZwpShellV1CapabilityHandler]struct{}
}
// initZwpShellV1 initializes the ZwpShellV1 object's handler maps
func (ret *ZwpShellV1) initZwpShellV1() {
	ret.privateZwpShellV1Capabilitys = make(map[ZwpShellV1CapabilityHandler]struct{})
}
// NewZwpShellV1 is a constructor for the ZwpShellV1 object
func NewZwpShellV1(ctx *Context) *ZwpShellV1 {
	ret := new(ZwpShellV1)
	ret.initZwpShellV1()
	ctx.Register(ret)
	return ret
}
// Release release the wl_fullscreen_shell interface
func (p *ZwpShellV1) Release() (error) {
	
	return p.Context().SendRequest(p, 0)
}
// PresentSurface present surface for display
func (p *ZwpShellV1) PresentSurface(Surface *Surface, Method uint32, Output *Output) (error) {
	
	return p.Context().SendRequest(p, 1, Surface, Method, Output)
}
// PresentSurfaceForMode present surface for display at a particular mode
func (p *ZwpShellV1) PresentSurfaceForMode(Surface *Surface, Output *Output, Framerate int32) (*ZwpShellModeFeedbackV1, error) {
	retFeedback := NewZwpShellModeFeedbackV1(p.Context())
	return retFeedback, p.Context().SendRequest(p, 2, Surface, Output, Framerate, retFeedback)
}
// Dispatch dispatches event for object ZwpShellV1
func (p *ZwpShellV1) Dispatch(event *Event) {
	switch event.Opcode {
	case 0:
		if len(p.privateZwpShellV1Capabilitys) > 0 {
			ev := ZwpShellV1CapabilityEvent{}
			ev.Capability = event.Uint32()
			p.mu.RLock()
			for h := range p.privateZwpShellV1Capabilitys {
				h.HandleZwpShellV1Capability(ev)
			}
			p.mu.RUnlock()
		}

	}
}
// ZwpShellV1CapabilityEvent is the advertises a capability of the compositor
type ZwpShellV1CapabilityEvent struct {
	// Capability is the 
	Capability uint32

}
// ZwpShellV1CapabilityHandler is the handler interface for ZwpShellV1CapabilityEvent
type ZwpShellV1CapabilityHandler interface {
	HandleZwpShellV1Capability(ZwpShellV1CapabilityEvent)
}

// AddCapabilityHandler adds the Capability handler
func (p *ZwpShellV1) AddCapabilityHandler(h ZwpShellV1CapabilityHandler) {
	if h != nil {
		p.mu.Lock()
		p.privateZwpShellV1Capabilitys[h] = struct{}{}
		p.mu.Unlock()
	}
}

// RemoveCapabilityHandler removes the Capability handler
func (p *ZwpShellV1) RemoveCapabilityHandler(h ZwpShellV1CapabilityHandler) {
	p.mu.Lock()
	defer p.mu.Unlock()

	delete (p.privateZwpShellV1Capabilitys, h)
}
// ZwpShellModeFeedbackV1 
type ZwpShellModeFeedbackV1 struct {
	BaseProxy
	mu sync.RWMutex
	privateZwpShellModeFeedbackV1ModeSuccessfuls map[ZwpShellModeFeedbackV1ModeSuccessfulHandler]struct{}
	privateZwpShellModeFeedbackV1ModeFaileds map[ZwpShellModeFeedbackV1ModeFailedHandler]struct{}
	privateZwpShellModeFeedbackV1PresentCancelleds map[ZwpShellModeFeedbackV1PresentCancelledHandler]struct{}
}
// initZwpShellModeFeedbackV1 initializes the ZwpShellModeFeedbackV1 object's handler maps
func (ret *ZwpShellModeFeedbackV1) initZwpShellModeFeedbackV1() {
	ret.privateZwpShellModeFeedbackV1ModeSuccessfuls = make(map[ZwpShellModeFeedbackV1ModeSuccessfulHandler]struct{})
	ret.privateZwpShellModeFeedbackV1ModeFaileds = make(map[ZwpShellModeFeedbackV1ModeFailedHandler]struct{})
	ret.privateZwpShellModeFeedbackV1PresentCancelleds = make(map[ZwpShellModeFeedbackV1PresentCancelledHandler]struct{})
}
// NewZwpShellModeFeedbackV1 is a constructor for the ZwpShellModeFeedbackV1 object
func NewZwpShellModeFeedbackV1(ctx *Context) *ZwpShellModeFeedbackV1 {
	ret := new(ZwpShellModeFeedbackV1)
	ret.initZwpShellModeFeedbackV1()
	ctx.Register(ret)
	return ret
}
// Dispatch dispatches event for object ZwpShellModeFeedbackV1
func (p *ZwpShellModeFeedbackV1) Dispatch(event *Event) {
	switch event.Opcode {
	case 0:
		if len(p.privateZwpShellModeFeedbackV1ModeSuccessfuls) > 0 {
			ev := ZwpShellModeFeedbackV1ModeSuccessfulEvent{}
			p.mu.RLock()
			for h := range p.privateZwpShellModeFeedbackV1ModeSuccessfuls {
				h.HandleZwpShellModeFeedbackV1ModeSuccessful(ev)
			}
			p.mu.RUnlock()
		}
	case 1:
		if len(p.privateZwpShellModeFeedbackV1ModeFaileds) > 0 {
			ev := ZwpShellModeFeedbackV1ModeFailedEvent{}
			p.mu.RLock()
			for h := range p.privateZwpShellModeFeedbackV1ModeFaileds {
				h.HandleZwpShellModeFeedbackV1ModeFailed(ev)
			}
			p.mu.RUnlock()
		}
	case 2:
		if len(p.privateZwpShellModeFeedbackV1PresentCancelleds) > 0 {
			ev := ZwpShellModeFeedbackV1PresentCancelledEvent{}
			p.mu.RLock()
			for h := range p.privateZwpShellModeFeedbackV1PresentCancelleds {
				h.HandleZwpShellModeFeedbackV1PresentCancelled(ev)
			}
			p.mu.RUnlock()
		}

	}
}
// ZwpShellModeFeedbackV1ModeSuccessfulEvent is the mode switch succeeded
type ZwpShellModeFeedbackV1ModeSuccessfulEvent struct {

}
// ZwpShellModeFeedbackV1ModeFailedEvent is the mode switch failed
type ZwpShellModeFeedbackV1ModeFailedEvent struct {

}
// ZwpShellModeFeedbackV1PresentCancelledEvent is the mode switch cancelled
type ZwpShellModeFeedbackV1PresentCancelledEvent struct {

}
// ZwpShellModeFeedbackV1ModeSuccessfulHandler is the handler interface for ZwpShellModeFeedbackV1ModeSuccessfulEvent
type ZwpShellModeFeedbackV1ModeSuccessfulHandler interface {
	HandleZwpShellModeFeedbackV1ModeSuccessful(ZwpShellModeFeedbackV1ModeSuccessfulEvent)
}

// AddModeSuccessfulHandler adds the ModeSuccessful handler
func (p *ZwpShellModeFeedbackV1) AddModeSuccessfulHandler(h ZwpShellModeFeedbackV1ModeSuccessfulHandler) {
	if h != nil {
		p.mu.Lock()
		p.privateZwpShellModeFeedbackV1ModeSuccessfuls[h] = struct{}{}
		p.mu.Unlock()
	}
}

// RemoveModeSuccessfulHandler removes the ModeSuccessful handler
func (p *ZwpShellModeFeedbackV1) RemoveModeSuccessfulHandler(h ZwpShellModeFeedbackV1ModeSuccessfulHandler) {
	p.mu.Lock()
	defer p.mu.Unlock()

	delete (p.privateZwpShellModeFeedbackV1ModeSuccessfuls, h)
}
// ZwpShellModeFeedbackV1ModeFailedHandler is the handler interface for ZwpShellModeFeedbackV1ModeFailedEvent
type ZwpShellModeFeedbackV1ModeFailedHandler interface {
	HandleZwpShellModeFeedbackV1ModeFailed(ZwpShellModeFeedbackV1ModeFailedEvent)
}

// AddModeFailedHandler adds the ModeFailed handler
func (p *ZwpShellModeFeedbackV1) AddModeFailedHandler(h ZwpShellModeFeedbackV1ModeFailedHandler) {
	if h != nil {
		p.mu.Lock()
		p.privateZwpShellModeFeedbackV1ModeFaileds[h] = struct{}{}
		p.mu.Unlock()
	}
}

// RemoveModeFailedHandler removes the ModeFailed handler
func (p *ZwpShellModeFeedbackV1) RemoveModeFailedHandler(h ZwpShellModeFeedbackV1ModeFailedHandler) {
	p.mu.Lock()
	defer p.mu.Unlock()

	delete (p.privateZwpShellModeFeedbackV1ModeFaileds, h)
}
// ZwpShellModeFeedbackV1PresentCancelledHandler is the handler interface for ZwpShellModeFeedbackV1PresentCancelledEvent
type ZwpShellModeFeedbackV1PresentCancelledHandler interface {
	HandleZwpShellModeFeedbackV1PresentCancelled(ZwpShellModeFeedbackV1PresentCancelledEvent)
}

// AddPresentCancelledHandler adds the PresentCancelled handler
func (p *ZwpShellModeFeedbackV1) AddPresentCancelledHandler(h ZwpShellModeFeedbackV1PresentCancelledHandler) {
	if h != nil {
		p.mu.Lock()
		p.privateZwpShellModeFeedbackV1PresentCancelleds[h] = struct{}{}
		p.mu.Unlock()
	}
}

// RemovePresentCancelledHandler removes the PresentCancelled handler
func (p *ZwpShellModeFeedbackV1) RemovePresentCancelledHandler(h ZwpShellModeFeedbackV1PresentCancelledHandler) {
	p.mu.Lock()
	defer p.mu.Unlock()

	delete (p.privateZwpShellModeFeedbackV1PresentCancelleds, h)
}
