// This file is autogenerated from: xdg-decoration-unstable-v1.xml
// Do not edit

// Package xdg implements the xdg_decoration_unstable_v1 protocol
package xdg

import (
	"sync"

)
// ZxdgToplevelDecorationV1ErrorUnconfiguredBuffer means xdg_toplevel has a buffer attached before configure
const ZxdgToplevelDecorationV1ErrorUnconfiguredBuffer = 0

// ZxdgToplevelDecorationV1ErrorAlreadyConstructed means xdg_toplevel already has a decoration object
const ZxdgToplevelDecorationV1ErrorAlreadyConstructed = 1

// ZxdgToplevelDecorationV1ErrorOrphaned means xdg_toplevel destroyed before the decoration object
const ZxdgToplevelDecorationV1ErrorOrphaned = 2

// ZxdgToplevelDecorationV1ErrorInvalidMode means invalid mode
const ZxdgToplevelDecorationV1ErrorInvalidMode = 3

// ZxdgToplevelDecorationV1ModeClientSide means no server-side window decoration
const ZxdgToplevelDecorationV1ModeClientSide = 1

// ZxdgToplevelDecorationV1ModeServerSide means server-side window decoration
const ZxdgToplevelDecorationV1ModeServerSide = 2

// ZxdgDecorationManagerV1 window decoration manager
type ZxdgDecorationManagerV1 struct {
	BaseProxy
}
// NewZxdgDecorationManagerV1 is a constructor for the ZxdgDecorationManagerV1 object
func NewZxdgDecorationManagerV1(ctx *Context) *ZxdgDecorationManagerV1 {
	ret := new(ZxdgDecorationManagerV1)
	ctx.Register(ret)
	return ret
}
// Destroy destroy the decoration manager object
func (p *ZxdgDecorationManagerV1) Destroy() (error) {
	
	return p.Context().SendRequest(p, 0)
}
// GetToplevelDecoration create a new toplevel decoration object
func (p *ZxdgDecorationManagerV1) GetToplevelDecoration(Toplevel *Toplevel) (*ZxdgToplevelDecorationV1, error) {
	retId := NewZxdgToplevelDecorationV1(p.Context())
	return retId, p.Context().SendRequest(p, 1, retId, Toplevel)
}
// Dispatch dispatches event for object ZxdgDecorationManagerV1
func (p *ZxdgDecorationManagerV1) Dispatch(event *Event) {
	switch event.Opcode {

	}
}
// ZxdgToplevelDecorationV1 decoration object for a toplevel surface
type ZxdgToplevelDecorationV1 struct {
	BaseProxy
	mu sync.RWMutex
	privateZxdgToplevelDecorationV1Configures map[ZxdgToplevelDecorationV1ConfigureHandler]struct{}
}
// initZxdgToplevelDecorationV1 initializes the ZxdgToplevelDecorationV1 object's handler maps
func (ret *ZxdgToplevelDecorationV1) initZxdgToplevelDecorationV1() {
	ret.privateZxdgToplevelDecorationV1Configures = make(map[ZxdgToplevelDecorationV1ConfigureHandler]struct{})
}
// NewZxdgToplevelDecorationV1 is a constructor for the ZxdgToplevelDecorationV1 object
func NewZxdgToplevelDecorationV1(ctx *Context) *ZxdgToplevelDecorationV1 {
	ret := new(ZxdgToplevelDecorationV1)
	ret.initZxdgToplevelDecorationV1()
	ctx.Register(ret)
	return ret
}
// Destroy destroy the decoration object
func (p *ZxdgToplevelDecorationV1) Destroy() (error) {
	
	return p.Context().SendRequest(p, 0)
}
// SetMode set the decoration mode
func (p *ZxdgToplevelDecorationV1) SetMode(Mode uint32) (error) {
	
	return p.Context().SendRequest(p, 1, Mode)
}
// UnsetMode unset the decoration mode
func (p *ZxdgToplevelDecorationV1) UnsetMode() (error) {
	
	return p.Context().SendRequest(p, 2)
}
// Dispatch dispatches event for object ZxdgToplevelDecorationV1
func (p *ZxdgToplevelDecorationV1) Dispatch(event *Event) {
	switch event.Opcode {
	case 0:
		if len(p.privateZxdgToplevelDecorationV1Configures) > 0 {
			ev := ZxdgToplevelDecorationV1ConfigureEvent{}
			ev.Mode = event.Uint32()
			p.mu.RLock()
			for h := range p.privateZxdgToplevelDecorationV1Configures {
				h.HandleZxdgToplevelDecorationV1Configure(ev)
			}
			p.mu.RUnlock()
		}

	}
}
// ZxdgToplevelDecorationV1ConfigureEvent is the notify a decoration mode change
type ZxdgToplevelDecorationV1ConfigureEvent struct {
	// Mode is the the decoration mode
	Mode uint32

}
// ZxdgToplevelDecorationV1ConfigureHandler is the handler interface for ZxdgToplevelDecorationV1ConfigureEvent
type ZxdgToplevelDecorationV1ConfigureHandler interface {
	HandleZxdgToplevelDecorationV1Configure(ZxdgToplevelDecorationV1ConfigureEvent)
}

// AddConfigureHandler adds the Configure handler
func (p *ZxdgToplevelDecorationV1) AddConfigureHandler(h ZxdgToplevelDecorationV1ConfigureHandler) {
	if h != nil {
		p.mu.Lock()
		p.privateZxdgToplevelDecorationV1Configures[h] = struct{}{}
		p.mu.Unlock()
	}
}

// RemoveConfigureHandler removes the Configure handler
func (p *ZxdgToplevelDecorationV1) RemoveConfigureHandler(h ZxdgToplevelDecorationV1ConfigureHandler) {
	p.mu.Lock()
	defer p.mu.Unlock()

	delete (p.privateZxdgToplevelDecorationV1Configures, h)
}
