// +build ignore

package main

import (
	"encoding/binary"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
)

func main() {
	// Change to the shaders directory
	if err := os.Chdir("shaders"); err != nil {
		fmt.Fprintf(os.Stderr, "Failed to change to shaders directory: %v\n", err)
		os.Exit(1)
	}

	shaders := []struct {
		source string
		stage  string
		output string
		goFile string
		varName string
	}{
		{"vertex.glsl", "vert", "vertex.spv", "../vertex_shader.go", "vs_spirv_source"},
		{"fragment.glsl", "frag", "fragment.spv", "../fragment_shader.go", "fs_spirv_source"},
	}

	for _, shader := range shaders {
		// Compile GLSL to SPIR-V using glslangValidator
		cmd := exec.Command("glslangValidator", "-V", "-S", shader.stage, shader.source, "-o", shader.output)
		cmd.Stdout = os.Stdout
		cmd.Stderr = os.Stderr
		
		if err := cmd.Run(); err != nil {
			fmt.Fprintf(os.Stderr, "Failed to compile %s: %v\n", shader.source, err)
			fmt.Fprintf(os.Stderr, "Make sure glslangValidator is installed (sudo apt install glslang-tools or sudo dnf install glslang)\n")
			os.Exit(1)
		}

		// Read the compiled SPIR-V binary
		data, err := os.ReadFile(shader.output)
		if err != nil {
			fmt.Fprintf(os.Stderr, "Failed to read %s: %v\n", shader.output, err)
			os.Exit(1)
		}

		// Convert to uint32 array
		if len(data)%4 != 0 {
			fmt.Fprintf(os.Stderr, "SPIR-V file %s has invalid size (not multiple of 4)\n", shader.output)
			os.Exit(1)
		}

		uint32Data := make([]uint32, len(data)/4)
		for i := 0; i < len(uint32Data); i++ {
			uint32Data[i] = binary.LittleEndian.Uint32(data[i*4 : (i+1)*4])
		}

		// Generate Go source file
		goFile, err := os.Create(shader.goFile)
		if err != nil {
			fmt.Fprintf(os.Stderr, "Failed to create %s: %v\n", shader.goFile, err)
			os.Exit(1)
		}
		defer goFile.Close()

		fmt.Fprintf(goFile, "package main\n\n")
		fmt.Fprintf(goFile, "// Code generated by go generate; DO NOT EDIT.\n")
		fmt.Fprintf(goFile, "// Generated from %s\n\n", shader.source)
		fmt.Fprintf(goFile, "var %s = []uint32{\n", shader.varName)

		// Write data in rows of 8 values for readability
		for i := 0; i < len(uint32Data); i++ {
			if i%8 == 0 {
				fmt.Fprintf(goFile, "\t")
			}
			fmt.Fprintf(goFile, "0x%08x", uint32Data[i])
			{
				fmt.Fprintf(goFile, ", ")
			}
			if i%8 == 7 {
				fmt.Fprintf(goFile, "\n")
			}
		}
		if len(uint32Data)%8 != 0 {
			fmt.Fprintf(goFile, "\n")
		}
		fmt.Fprintf(goFile, "}\n")

		fmt.Printf("Generated %s from %s (%d uint32 values)\n", 
			filepath.Base(shader.goFile), shader.source, len(uint32Data))
	}
}
